# Generated by Django 3.1.4 on 2020-12-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('sisalla', models.FloatField()),
                ('ulkona', models.FloatField()),
                ('jarvessa', models.FloatField()),
                ('rauhalassa', models.FloatField()),
                ('kellarissa', models.FloatField()),
            ],
        ),
    ]
