# Generated by Django 3.1.4 on 2020-12-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampotilat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='jarvessa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='kellarissa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='rauhalassa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sisalla',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='ulkona',
            field=models.FloatField(null=True),
        ),
    ]
