# Generated by Django 3.1.4 on 2020-12-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampotilat', '0002_auto_20201230_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.IntegerField(unique=True),
        ),
    ]
