# Generated by Django 3.1.4 on 2020-12-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampotilat', '0003_auto_20201230_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='saunassa',
            field=models.FloatField(null=True),
        ),
    ]
